Enhance release workflow by adding input validation for 'create_okd_release_pr' operation and updating 'ocp_version' requirement to optional.
The inputs bundle-community-okd requieredo set ocp_version. The inpue build_and_push_images not required ocp_version but they both  share the same interface, sine it's mandatory for one of the two, it was set for both.

The input for ocp_version in the rest of medik8s operator is not required. To aligned th behavior across all operators, adding input validation task only for release to bundle-community-okd.

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -17,8 +17,8 @@ on:
        description: "The previous version, used for the CVS's `replaces` field, without the leading `v`"
        required: true
      ocp_version:
-       description: "The target OCP version for the release (mandatory for create_okd_release_pr option)"
-       required: true
+       description: "The target OCP version for the release (mandatory for 'create_okd_release_pr' operation)"
+       required: false
 
 permissions:
   contents: write
@@ -88,7 +88,21 @@ jobs:
           files: >
             Manifests:bundle/
 
+  # This new job validates the inputs for the 'create_okd_release_pr' operation.
+  validate_pr_inputs:
+    name: Validate Inputs
+    if: ${{ inputs.operation == 'create_okd_release_pr' }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check if ocp_version is provided
+        if: ${{ inputs.ocp_version == '' }}
+        run: |
+          echo "Error: The 'ocp_version' input is mandatory when the operation is 'create_okd_release_pr'."
+          exit 1
+
   create_okd_release_pr:
+    # This job now depends on the validation job.
+    needs: validate_pr_inputs
     if: inputs.operation == 'create_okd_release_pr'
     uses: medik8s/.github/.github/workflows/release_community_bundle_parametric.yaml@main
     secrets: inherit
